"""initial schema

Revision ID: 1e6e580af725
Revises: 
Create Date: 2026-07-15 19:27:40.256690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6e580af725'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_active', 'users', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('ix_users_api_key_hash', 'users', ['api_key_hash'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('short_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index('ix_short_links_active_code', 'short_links', ['short_code'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('ix_short_links_short_code', 'short_links', ['short_code'], unique=True)
    op.create_index('ix_short_links_user_created', 'short_links', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_short_links_user_id', 'short_links', ['user_id'], unique=False)
    op.create_table('link_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['short_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_link_clicks_clicked_at', 'link_clicks', ['clicked_at'], unique=False)
    op.create_index('ix_link_clicks_link_id', 'link_clicks', ['link_id'], unique=False)
    op.create_index('ix_link_clicks_link_time', 'link_clicks', ['link_id', 'clicked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_clicks_link_time', table_name='link_clicks')
    op.drop_index('ix_link_clicks_link_id', table_name='link_clicks')
    op.drop_index('ix_link_clicks_clicked_at', table_name='link_clicks')
    op.drop_table('link_clicks')
    op.drop_index('ix_short_links_user_id', table_name='short_links')
    op.drop_index('ix_short_links_user_created', table_name='short_links')
    op.drop_index('ix_short_links_short_code', table_name='short_links')
    op.drop_index('ix_short_links_active_code', table_name='short_links', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('short_links')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_api_key_hash', table_name='users')
    op.drop_index('ix_users_active', table_name='users', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('users')
    # ### end Alembic commands ###
